/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.asaid.view;

import br.com.asaid.dto.AdminDTO;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JInternalFrame;

public class TelaInicialVIEW extends javax.swing.JFrame {

    AdminDTO adminDTO = new AdminDTO();
    /**
     * Creates new form TelaInicialVIEW
     */
    public TelaInicialVIEW(AdminDTO adminDTO) {
        this.adminDTO = adminDTO;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("AsAid");
        lblusuario.setText(lblusuario.getText() + this.adminDTO.getNome_user().toUpperCase());

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon imageicon = new ImageIcon(getClass().getResource("imagens/tela.png"));
        Image image = imageicon.getImage();
        desktopPane = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics graphics){
                graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        lblusuario = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        MenuCadastros = new javax.swing.JMenu();
        MenuItemAdministrador = new javax.swing.JMenuItem();
        MenuItemCliente = new javax.swing.JMenuItem();
        MenuItemAssist = new javax.swing.JMenuItem();
        MenuItemProduto = new javax.swing.JMenuItem();
        MenuAtualizar = new javax.swing.JMenu();
        MenuItemAtualizarAssistencia = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();
        MenuItemSairSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblusuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(240, 240, 240));
        lblusuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblusuario.setText("Você está logado como: ");
        desktopPane.add(lblusuario);
        lblusuario.setBounds(760, 10, 250, 15);

        MenuCadastros.setMnemonic('f');
        MenuCadastros.setText("Cadastros");

        MenuItemAdministrador.setMnemonic('o');
        MenuItemAdministrador.setText("Administrador");
        MenuItemAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAdministradorActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuItemAdministrador);

        MenuItemCliente.setMnemonic('s');
        MenuItemCliente.setText("Cliente");
        MenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemClienteActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuItemCliente);

        MenuItemAssist.setText("Assistência");
        MenuItemAssist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAssistActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuItemAssist);

        MenuItemProduto.setText("Produto");
        MenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProdutoActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuItemProduto);

        menuBar.add(MenuCadastros);

        MenuAtualizar.setText("Atualizar");

        MenuItemAtualizarAssistencia.setText("Assistência");
        MenuItemAtualizarAssistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAtualizarAssistenciaActionPerformed(evt);
            }
        });
        MenuAtualizar.add(MenuItemAtualizarAssistencia);

        menuBar.add(MenuAtualizar);

        MenuSair.setMnemonic('h');
        MenuSair.setText("Sair");

        MenuItemSairSistema.setMnemonic('c');
        MenuItemSairSistema.setText("Sair do sistema");
        MenuItemSairSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItemSairSistemaMouseClicked(evt);
            }
        });
        MenuItemSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSairSistemaActionPerformed(evt);
            }
        });
        MenuSair.add(MenuItemSairSistema);

        menuBar.add(MenuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSairSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItemSairSistemaMouseClicked
 
    }//GEN-LAST:event_MenuItemSairSistemaMouseClicked

    private void MenuItemSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSairSistemaActionPerformed
        sair();
    }//GEN-LAST:event_MenuItemSairSistemaActionPerformed

    private void MenuItemAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAdministradorActionPerformed
        CadastroVIEW cadastroVIEW = new CadastroVIEW();
        this.desktopPane.add(cadastroVIEW);
        cadastroVIEW.setVisible(true);
        cadastroVIEW.setPosicao();
    }//GEN-LAST:event_MenuItemAdministradorActionPerformed

    private void MenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemClienteActionPerformed
        ClienteVIEW clienteVIEW = new ClienteVIEW();
        this.desktopPane.add(clienteVIEW);
        clienteVIEW.setVisible(true);
        clienteVIEW.setPosicao();
    }//GEN-LAST:event_MenuItemClienteActionPerformed

    private void MenuItemAssistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAssistActionPerformed
        AssistenciaVIEW assistenciaVIEW = new AssistenciaVIEW();
        this.desktopPane.add(assistenciaVIEW);
        assistenciaVIEW.setVisible(true);
        assistenciaVIEW.setPosicao();                               
    }//GEN-LAST:event_MenuItemAssistActionPerformed

    private void MenuItemAtualizarAssistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAtualizarAssistenciaActionPerformed
        AtualizarAssistVIEW atualizarAssistVIEW = new AtualizarAssistVIEW();
        this.desktopPane.add(atualizarAssistVIEW);
        atualizarAssistVIEW.setVisible(true);
        atualizarAssistVIEW.setPosicao();
    }//GEN-LAST:event_MenuItemAtualizarAssistenciaActionPerformed

    private void MenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProdutoActionPerformed
        ProdutoVIEW produtoVIEW = new ProdutoVIEW(adminDTO);
        this.desktopPane.add(produtoVIEW);
        produtoVIEW.setVisible(true);
        produtoVIEW.setPosicao();
    }//GEN-LAST:event_MenuItemProdutoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    private void sair(){
        Object[] options = { "Sair", "Cancelar" };
        if(JOptionPane.showOptionDialog(null, "Deseja Sair do Sistema", "Informação", 
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 0){
            System.exit(0);
        } 
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAtualizar;
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenuItem MenuItemAdministrador;
    private javax.swing.JMenuItem MenuItemAssist;
    private javax.swing.JMenuItem MenuItemAtualizarAssistencia;
    private javax.swing.JMenuItem MenuItemCliente;
    private javax.swing.JMenuItem MenuItemProduto;
    private javax.swing.JMenuItem MenuItemSairSistema;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
